version: "3"
services: 
  springboot-app:
   # container_name: spring-app
    image: auth-app
    restart: always
    build: ./users-microservice
    ports:
      - 8080:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: db_auth
      MYSQL_ROOT_PASSWORD: root
        